name: Build for Redox

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      id: build
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y -qq install rustup pkg-config libssl-dev libfuse3-dev
        rustup toolchain install stable
        rustup target add x86_64-unknown-redox


    - name: Install Redoxer
      run: cargo install redoxer

    - name: Setup Redox toolchain
      run: redoxer toolchain --update

    - name: Build for Redox
      run: redoxer build

    - name: Check result (temp)
      run: |
        ls -lh target/x86_64-unknown-redox/release

